global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.147.18.252:9100']

  - job_name: 'jbpmn'
    static_configs:
      - targets: ['10.147.18.252:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['10.147.18.252:80']

  - job_name: 'grafana'
    static_configs:
      - targets: ['10.147.18.252:3000']
