global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'jbpmn'
    static_configs:
      - targets: ['jbpmn:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
